/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EasyAToken } from "./EasyAToken";
export type { StockExchange } from "./StockExchange";
export type { Voting } from "./Voting";
