/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EasyAToken__factory } from "./EasyAToken__factory";
export { StockExchange__factory } from "./StockExchange__factory";
export { Voting__factory } from "./Voting__factory";
